import { useState } from 'react';
import { Link } from 'react-router-dom';
import { archiveEntries, originalScreens } from '@/data/projectLife';
import { SectionHeader } from '@/components/pl/Elements';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

export default function Archive() {
  const [category, setCategory] = useState('ALL');
  return <div className="page-container archive-page"><SectionHeader label="ARCHIVE / EVERYTHING BECOMES PART OF THE STORY" title="Nothing disappears." description="Every experiment teaches the next one." /><section className="original-site" id="original-site"><div className="original-heading"><span className="eyebrow">PRESERVED / ORIGINAL SITE</span><h2>Before the lab,<br />there was a desktop.</h2><p>The earlier home of Project Life. Galaxy wallpaper, familiar windows, an application dock, and a player for the late nights. A different expression of the same curiosity.</p><span className="eyebrow">SCREENSHOTS CAPTURED SEPTEMBER 15, 2026</span></div><div className="archive-gallery">{originalScreens.map((screen,index)=><figure key={screen.src}><Dialog><DialogTrigger asChild><button className="archive-image-button" aria-label={`Enlarge original ${screen.title.toLowerCase()} screenshot`}><img src={screen.src} alt={screen.alt} loading="lazy"/><span className="image-enlarge eyebrow">EXPAND ↗</span></button></DialogTrigger><DialogContent className="archive-lightbox"><DialogTitle>Original Project Life — {screen.title}</DialogTitle><DialogDescription>{screen.caption} Captured September 15, 2026.</DialogDescription><img src={screen.src} alt={screen.alt}/></DialogContent></Dialog><figcaption><span className="eyebrow">0{index+1} / {screen.title}</span><p>{screen.caption}</p></figcaption></figure>)}</div><Link className="text-link" to="/journal">READ THE JOURNAL BEHIND THESE SCREENS →</Link></section><section className="section"><div className="section-intro"><span className="eyebrow">THE EXPERIMENTS</span><h2>Iterations, not endings.</h2></div><div className="filter-bar" aria-label="Filter archive">{['ALL',...new Set(archiveEntries.map(e=>e.category))].map(c=><button key={c} aria-pressed={c === category} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="archive-timeline">{archiveEntries.filter(e=>category === 'ALL' || category === e.category).map(entry=><article key={entry.name}><span className="eyebrow">{entry.category}</span><h3>{entry.name} <span>→ {entry.outcome}</span></h3><p>{entry.description}</p></article>)}</div></section></div>;
}
