import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react';
import { experiments } from '@/data/projectLife';
import { ExperimentCard, SectionHeader, StatusBadge, WindowFrame } from '@/components/pl/Elements';

export function Build() { return <div className="page-container inner-page"><SectionHeader label="THE LAB" title="Things being experimented with." description="Small software. Ordinary questions. A few attempts to make life a little better."/><div className="experiment-grid">{experiments.map((project,index)=><ExperimentCard {...{project,index}} key={project.id}/>)}</div><p className="closing-note">Every project begins with an ordinary problem.<br/><Link className="text-link" to="/think">FOLLOW THE JOURNAL <ArrowRight size={16}/></Link></p></div>; }
export function ExperimentDetail() {
  const { slug } = useParams();
  const p = experiments.find(e=>e.id === slug);
  if (!p) return <div className="page-container inner-page"><SectionHeader label="THE LAB" title="Experiment not found."/><Link className="text-link" to="/lab">RETURN TO THE LAB →</Link></div>;
  return <div className="page-container inner-page experiment-page"><Link className="text-link back-link" to="/lab"><ArrowLeft size={16}/> THE LAB</Link><SectionHeader label="PROJECT LIFE / EXPERIMENT" title={p.name} description={p.description}/><div className="experiment-metadata"><StatusBadge>{p.status}</StatusBadge><span className="eyebrow">{p.category}</span></div><div className="detail-layout"><div><section><span className="eyebrow">THE IDEA</span><h2>{p.description}</h2><p>{p.detail}</p></section><section><span className="eyebrow">THE PROCESS</span><h2>Built one question at a time.</h2><p>The journal records the decisions, setbacks, and small milestones behind Project Life.</p><Link className="text-link" to="/think">READ THE JOURNAL <ArrowRight size={16}/></Link></section></div><WindowFrame title="CURRENT STATE"><StatusBadge>{p.status}</StatusBadge><p>{p.url ? 'Explore the current experiment and share what you find.' : 'An experiment in progress. Follow the journal for updates.'}</p>{p.url && <a className="primary-link" href={p.url} target="_blank" rel="noopener noreferrer">OPEN EXPERIMENT <ArrowUpRight size={16}/></a>}<a className="text-link" href={`mailto:supp.projectlif3@gmail.com?subject=${encodeURIComponent('Feedback: '+p.name)}`}>FEEDBACK THE LAB <ArrowRight size={16}/></a></WindowFrame></div></div>;
}
export function Builder() { return <div className="page-container inner-page builder-page"><SectionHeader label="THE BUILDER" title="A human, somewhere on Earth."/><div className="builder-layout"><WindowFrame title="IDENTITY / MANIFEST" className="builder-profile"><div className="profile-cv">CV<span className="status-dot"/></div><dl>{[['IDENTITY','Human / Earthling'],['ROLE','Builder'],['PLANET','Earth'],['STATUS','Experimenting']].map(([k,v])=><div key={k}><dt className="eyebrow">{k}</dt><dd>{v}</dd></div>)}</dl></WindowFrame><div className="builder-prose"><p>There is a person behind Project Life.</p><p>But this isn’t really a website about that person.<br/>It’s about the questions they can’t stop asking.</p><div className="builder-questions">{['How should we spend our time?', 'What makes something worth building?', 'Can technology make ordinary life a little easier?', 'What makes a life feel meaningful?', 'Can one person build useful things without waiting for permission?'].map(q=><p key={q}>{q}</p>)}</div><p>Project Life is where those questions become experiments.</p><p>Some work. Some don’t. Some become products. Some become lessons.<br/>Everything becomes part of the archive.</p><p className="builder-final">The identity of the builder isn’t particularly important.<br/>The experiments are.</p></div></div><section className="connect-section" id="connect"><span className="eyebrow">CONNECT</span><h2>Say hello.</h2><p>Have an idea? Found something broken? Have feedback about an experiment? Want to collaborate? Or simply want to say hello?</p><a className="primary-link" href="mailto:supp.projectlif3@gmail.com">SEND A MESSAGE <ArrowUpRight size={16}/></a><div className="connect-links eyebrow"><a href="mailto:supp.projectlif3@gmail.com">EMAIL</a><a href="https://buymeacoffee.com/projectlif3" target="_blank" rel="noopener noreferrer">BUY ME A COFFEE ↗</a></div></section></div>; }
